export const CREATE_OR_EDIT_SHOPPING_RECORD = 'list/CREATE_OR_EDIT_SHOPPING_RECORD';
export const ON_CHANGE_FORM_DATA = 'list/ON_CHANGE_FORM_DATA';
export const SAVE_SHOPPING_RECORD = 'list/SAVE_SHOPPING_RECORD';
export const DELETE_SHOPPING_RECORD = 'list/DELETE_SHOPPING_RECORD';
export const SEARCH_BY_NAME = 'list/SEARCH_BY_NAME';